------------Customer Shopping Behavior Analysis @Business Questions--------------
-----------Revenue Analysis-----------

---Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(Purchase_Amount) AS Total_Revenue 
FROM customer 
GROUP BY gender;

---Q2.What is the revenue contribution of each age group?
SELECT age_group, SUM(Purchase_Amount) AS Total_Revenue 
FROM customer 
GROUP BY age_group
ORDER BY age_group DESC;

-----------Discount & Pricing Insights-----------
--Q3.Which top 20 customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied= 'Yes' 
AND purchase_amount > (
	SELECT AVG(purchase_amount) FROM customer)
	ORDER BY purchase_amount DESC 
	LIMIT 20;

---Q4.Which 5 products have the highest percentage of purchases with discounts applied?
SELECT * FROM customer;
SELECT item_purchased,
       COUNT(*) AS total_purchases,
       ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
       / COUNT(*),2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-----------------Product Performance---------------------
---Q5.Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

---Q6.What are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (PARTITION BY category 
                              ORDER BY COUNT(*) DESC) AS rank_num
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE rank_num <= 3;

---OR

SELECT category, item_purchased, COUNT(*) AS purchase_count
FROM customer
GROUP BY category, item_purchased
ORDER BY category, purchase_count DESC;


------------Shipping & Purchase Behavior-------------------
---Q7.Compare the average purchase amounts between Standard and Express shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

--------------Subscription & Customer Value------------------
---Q8.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
	ROUND(AVG(purchase_amount),2) AS avg_spend,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

---Q9.Are repeat buyers (more than 5 previous purchases) more likely to subscribe?
SELECT 
CASE 
    WHEN previous_purchases > 5 THEN 'Repeat Buyer'
    ELSE 'Others'
END AS buyer_type,
subscription_status,
COUNT(*) AS total_customers
FROM customer
GROUP BY buyer_type, subscription_status;

----------Customer Segmentation--------------
---Q10.Segment customers INTO New, Returning, and Loyal based on previous purchases and show the count of each segment.
SELECT 
CASE 
    WHEN previous_purchases = 0 THEN 'New'
    WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS total_customers
FROM customer
GROUP BY customer_segment;




